version: '3.8'

services:
  # Base de datos PostgreSQL
  postgres:
    image: postgres:15-alpine
    container_name: socialnetwork-postgres
    environment:
      POSTGRES_DB: socialnetwork
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - socialnetwork-network

  # Backend API
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: socialnetwork-backend
    environment:
      NODE_ENV: development
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USERNAME: postgres
      DB_PASSWORD: password
      DB_NAME: socialnetwork
      JWT_SECRET: tu-secreto-super-seguro-cambiar-en-produccion
      PORT: 3001
    ports:
      - "3001:3001"
    depends_on:
      - postgres
    networks:
      - socialnetwork-network
    volumes:
      - ./backend:/app
      - /app/node_modules

  # Frontend React
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: socialnetwork-frontend
    environment:
      REACT_APP_API_URL: http://localhost:3001
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - socialnetwork-network

networks:
  socialnetwork-network:
    driver: bridge

volumes:
  postgres_data: 